import type { Metadata } from 'next';
// import { Inter } from 'next/font/google' // Try out the geist font 😮‍💨 -> https://vercel.com/font/sans
import { GeistSans } from 'geist/font/sans'; // Geist also has a mono font
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';
import './globals.css';
import { SharedNav } from '@/components/nav/shared-nav';
import { Footer } from '@/components/footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			{/* <body className={GeistSans.className}>{children}</body> */}
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					GeistSans.className
				)}
			>
				<ThemeProvider
					disableTransitionOnChange
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					<>
						<SharedNav />
						{children}
						<Footer />
					</>
				</ThemeProvider>
			</body>
		</html>
	);
}
