import type { Metadata } from 'next';
// import { Inter } from 'next/font/google' // Try out the geist font 😮‍💨 -> https://vercel.com/font/sans
import { GeistSans } from 'geist/font/sans'; // Geist also has a mono font
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';
import './globals.css';
import { dir } from 'i18next';
import { languages } from '../i18n/settings';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export async function generateStaticParams() {
	return languages.map((lng) => ({ lng }));
}

export default function RootLayout({
	children,
	params: { lng }
}: {
	children: React.ReactNode;
	params: { lng: string };
}) {
	return (
		<html lang={lng} dir={dir(lng)}>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					GeistSans.className
				)}
			>
				<ThemeProvider
					disableTransitionOnChange
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
